---
version: 2.1

orbs: 
  cypress: cypress-io/cypress@2.0.0

jobs:
  npm-start:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
          - node_modules
      - run:
          name: npm start
          command: npm run start
          background: true
  unit-tests:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
          - node_modules
      - run:
          name: test
          command: npm run test
workflows:
  say-hello-workflow:
    jobs:
      - unit-tests
      - npm-start
      - cypress/install
      - cypress/run:
          requires:
            - npm-start
            - cypress/install