---
version: 2.1

jobs:
  unit-tests:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
          - node_modules
      - run:
          name: test
          command: npm run test
workflows:
  say-hello-workflow:
    jobs:
      - unit-tests